<?php
require_once dirname(__DIR__) . '/app/bootstrap.php';
$slug = isset($_GET['slug']) ? trim((string) $_GET['slug']) : '';
$statement = db()->prepare('SELECT * FROM categories WHERE slug = :slug AND is_active = 1 LIMIT 1');
$statement->execute(array(':slug' => $slug));
$category = $statement->fetch();
if (!$category) { http_response_code(404); exit('未找到该分类。'); }
$page = max(1, (int) (isset($_GET['page']) ? $_GET['page'] : 1));
$perPage = (int) setting('category_page_size', '0');
if ($perPage < 0) { $perPage = 24; }
$count = db()->prepare('SELECT COUNT(*) FROM websites WHERE category_id = :category_id AND is_active = 1');
$count->execute(array(':category_id' => (int) $category['id']));
$total = (int) $count->fetchColumn();
$totalPages = $perPage === 0 ? 1 : max(1, (int) ceil($total / $perPage));
$page = min($page, $totalPages);
$categorySql = 'SELECT w.*, h.primary_status, h.backup_status FROM websites w LEFT JOIN website_health h ON h.website_id = w.id WHERE w.category_id = :category_id AND w.is_active = 1 ORDER BY w.is_featured DESC, w.sort_order ASC, datetime(w.created_at) DESC, w.id DESC'; if ($perPage > 0) { $categorySql .= ' LIMIT :limit OFFSET :offset'; } $query = db()->prepare($categorySql); $query->bindValue(':category_id', (int) $category['id'], PDO::PARAM_INT); if ($perPage > 0) { $query->bindValue(':limit', $perPage, PDO::PARAM_INT); $query->bindValue(':offset', ($page - 1) * $perPage, PDO::PARAM_INT); } $query->execute();
$websites = $query->fetchAll();
$siteName = setting('site_name', app_config()['app_name']);
$categoryMobileGridColumns = in_array((int) setting('category_mobile_grid_columns', '1'), array(1, 2), true) ? (int) setting('category_mobile_grid_columns', '1') : 1;
$categoryGridColumns = in_array((int) setting('category_grid_columns', '4'), array(3, 4, 5, 6), true) ? (int) setting('category_grid_columns', '4') : 4;
$theme = isset($_COOKIE['site_navigator_theme']) ? rawurldecode((string) $_COOKIE['site_navigator_theme']) : setting('default_theme', 'daylight');
$allowed = array('daylight','night','forest','twilight','china-red','glazed-yellow','cloud-gray'); if (!in_array($theme, $allowed, true)) $theme = 'daylight';
$themeClass = $theme === 'daylight' ? '' : ' theme-' . $theme;
function category_page_url($slug, $page) { return '/category/?slug=' . rawurlencode($slug) . '&page=' . (int) $page; }
?><!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?= e($category['name']) ?> — <?= e($siteName) ?></title><link rel="stylesheet" href="/assets/css/app.css?v=<?= (int) filemtime(__DIR__ . '/assets/css/app.css') ?>"><style>
.category-page{--bg:#f5f7fb;--surface:#fff;--ink:#172033;--muted:#667085;--line:#e4e7ec;--brand:#3b82f6;min-height:100vh;background:var(--bg);color:var(--ink)}.category-page .category-wrap{max-width:1180px;margin:0 auto;padding:28px 22px 50px}.category-page .category-head{display:flex;align-items:center;justify-content:space-between;gap:16px;margin-bottom:24px}.category-page .category-head h1{margin:0;font-size:28px}.category-page .category-head p{color:var(--muted);margin:7px 0 0}.category-page .category-back{color:var(--brand);text-decoration:none}.category-page .website-grid{display:grid;grid-template-columns:repeat(<?= $categoryGridColumns ?>,minmax(0,1fr));gap:12px}.category-page .site-card{background:var(--surface);border:1px solid var(--line);border-radius:14px;padding:15px;min-height:105px}.category-page .site-link{display:flex;gap:12px;color:inherit;text-decoration:none}.category-page .favicon{width:40px;height:40px;border-radius:10px;object-fit:cover}.category-page .site-title{font-weight:700}.category-page .site-desc,.category-page .site-url{display:block;color:var(--muted);font-size:13px;margin-top:5px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.category-page .pagination{display:flex;gap:8px;justify-content:center;margin-top:28px}.category-page .pagination a{padding:8px 12px;border:1px solid var(--line);border-radius:8px;color:var(--ink);text-decoration:none;background:var(--surface)}.category-page .pagination .disabled{padding:8px 12px;border:1px solid var(--line);border-radius:8px;color:var(--muted);background:var(--surface);opacity:.55}.category-page .pagination .current{background:var(--brand);color:#fff;border-color:var(--brand)}.category-page.theme-night{--bg:#0b1120;--surface:#111827;--ink:#f3f6fb;--muted:#a9b5c7;--line:#29364b;--brand:#78a7ff}.category-page.theme-forest{--bg:#eef7f1;--line:#d5e8dc;--brand:#18845a}.category-page.theme-twilight{--bg:#f5f1fb;--line:#e4daf1;--brand:#7955c6}.category-page.theme-china-red{--bg:#fff5f5;--line:#f0c7ca;--brand:#c92d3a}.category-page.theme-glazed-yellow{--bg:#fffaf0;--line:#ead59a;--brand:#d99a08}.category-page.theme-cloud-gray{--bg:#f1f3f5;--line:#cbd1d8;--brand:#66717d}@media(max-width:700px){.category-page .website-grid{grid-template-columns:repeat(<?= $categoryMobileGridColumns ?>,minmax(0,1fr));gap:10px}.category-page .category-head{align-items:flex-start;flex-direction:column}.category-page .site-card{padding:12px}.category-page .site-link{gap:8px}.category-page .favicon{width:34px;height:34px}.category-page .site-title{font-size:14px}}
</style></head><body class="category-page<?= e($themeClass) ?>"><main class="category-wrap"><header class="category-head"><div><h1><?= e($category['name']) ?></h1><p>共 <?= $total ?> 个网站，当前第 <?= $page ?> / <?= $totalPages ?> 页</p></div><a class="category-back" href="/">返回导航首页</a></header><div class="website-grid"><?php foreach ($websites as $website): ?><article class="site-card"><a class="site-link" href="/go/?id=<?= (int) $website['id'] ?>" target="_blank" rel="noopener noreferrer"><?php if ($website['icon_path']): ?><img class="favicon" src="<?= e(website_icon_url($website['icon_path'])) ?>" alt=""><?php else: ?><span class="favicon fallback-icon">N</span><?php endif; ?><span><span class="site-title"><?= e($website['title']) ?></span><span class="site-desc"><?= e($website['description']) ?></span><span class="site-url"><?= e(parse_url($website['primary_url'], PHP_URL_HOST)) ?></span></span></a></article><?php endforeach; ?></div><?php if ($totalPages > 1): ?><nav class="pagination" aria-label="分类分页"><?php if ($page > 1): ?><a href="<?= e(category_page_url($category['slug'], $page - 1)) ?>">上一页</a><?php else: ?><span class="disabled">上一页</span><?php endif; ?><?php for ($i=1;$i<=$totalPages;$i++): ?><?php if ($i === $page): ?><span class="current"><?= $i ?></span><?php else: ?><a href="<?= e(category_page_url($category['slug'], $i)) ?>"><?= $i ?></a><?php endif; ?><?php endfor; ?><?php if ($page < $totalPages): ?><a href="<?= e(category_page_url($category['slug'], $page + 1)) ?>">下一页</a><?php else: ?><span class="disabled">下一页</span><?php endif; ?></nav><?php endif; ?></main></body></html>

<style>
.category-page .site-link > span:last-child { min-width: 0; overflow: hidden; }
.category-page .site-title { display: block; min-width: 0; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
.category-page .site-desc { max-width: 100%; }
.category-page .site-url { max-width: 100%; }
</style>
